FROM docker.io/library/alpine:latest
RUN apk add --no-cache zsh curl sudo shadow bash
RUN curl -sS https://starship.rs/install.sh | sh -s -- -y
COPY starship.toml /etc/starship.toml
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
