FROM docker.io/menci/archlinuxarm
RUN pacman -Sy --noconfirm zsh curl sudo && pacman -Scc --noconfirm
RUN curl -sS https://starship.rs/install.sh | sh -s -- -y
COPY starship.toml /etc/starship.toml
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
